apiVersion: apps/v1
kind: Deployment
metadata: 
    name: ip-echo-deployment
    labels:
        app: ip-echo
spec:
    replicas: 3
    selector:
        matchLabels:
            app: ip-echo
    template:
        metadata:
            labels:
                app: ip-echo
        spec:
            containers:
            -   name: ip-echo
                image: mattackard/ip-echo:1.0
                ports:
                -   containerPort: 8080